### ISSUE TITLE
隔壁qsign的

### ISSUE THREAD

**Issue by Kobe972** [rhwong/OlivOS-OneKey#5]
可以开放qsign的issue吗？我发现最新的qsign不包含txlib以及libs目录，请问这两个目录在哪找？除此之外，是否可以把之前版本的qsign发到xuyichang2003@gmail.com？我想要备份一下。现在旧版的qsign仍然能用，我认为可以在基于NTQQ的bot开发出来前暂时用旧版cqhttp替代

**Comment by rhwong** [comment]
release我传回去了
